In [1]:
import pandas as pd
import numpy as np

In [2]:
double = pd.read_csv("Medication One Row Extraction/Two Combination One Row.csv")
single = pd.read_csv("Medication Extraction/Double Combination.csv")

In [3]:
double.head()

   Unnamed: 0    ID  Line                Medication  PFS  Duration
0           1   MM1     1  Bortezomib, Lenalidomide  311       254
1           2   MM1     2      Stem cell transplant    1         1
2           3  MM10     1  Bortezomib, Lenalidomide   91        91
3           4  MM10     2              Lenalidomide   62         1
4           5  MM10     3              Lenalidomide  112        76

In [4]:
single.head()

,Unnamed: 0,ID,Line,DaysFromDxStart,DaysFromDxStop,MedTx,Duration,PFS
0,1,MM1,1,4,258,Lenalidomide,254,311
1,2,MM1,1,4,258,Bortezomib,254,311
2,3,MM1,2,315,316,Stem cell transplant,1,1
3,4,MM10,1,21,112,Bortezomib,91,91
4,5,MM10,1,21,112,Lenalidomide,91,91

In [7]:
line1 = double[double["Line"] == 1]
doubles = line1["Medication"].unique()
doubles

array(['Bortezomib, Lenalidomide', 'Bortezomib, Thalidomide',
       'Bortezomib, Cyclophosphamide', 'Adriamycin, Vincristine',
       'Melphalan, Prednisone', 'Bortezomib, Doxorubicin',
       'Doxorubicin, Vincristine', 'Liposomal doxorubicin, Vincristine',
       'Cyclophosphamide, Etoposide', 'Bortezomib, Prednisone',
       'Carfilzomib, Cyclophosphamide', 'Carfilzomib, Lenalidomide',
       'Bortezomib, Liposomal doxorubicin', 'Elotuzumab, Lenalidomide',
       'Adriamycin, Bortezomib', 'Carfilzomib, Pomalidomide',
       'Cyclophosphamide, Paciltaxel', 'Bortezomib, Rituximab'],
      dtype=object)

In [14]:
def getSingle(med):
    doubleT = double[(double["Line"] != 1) & (double["Medication"] == med) & (double["ID"] == ID)]
    if doubleT.shape[0] != 0:
        return doubleT.iloc[0]["PFS"]
    else:
        start = single[(single["Line"] == 1) & (single["MedTx"] == med) & (single["ID"] == ID)]["DaysFromDxStop"].values[0]
        stop =  single[(single["Line"] == 1) & (single["MedTx"] == med) & (single["ID"] == ID)]["DaysFromDxStart"].values[0]
        return start - stop

In [15]:
for AB in doubles:
    AandB = AB.split(", ")
    A = AandB[0]
    B = AandB[1]
    clm = ["ID", "PFS_" + AB, "PFS_" + A, "PFS_" + B]
    ABpd = pd.DataFrame(columns = clm)
    medAB = line1[line1["Medication"] == AB]
    medAB = medAB[["ID", "PFS"]]
    IDs = medAB["ID"]
    count = 0
    for ID in IDs:
        PFS_A = getSingle(A)
        PFS_B = getSingle(B)
        PFS_AB = medAB[medAB["ID"] == ID]["PFS"].values[0]
        ABpd.loc[count] = [ID, PFS_AB, PFS_A, PFS_B]
        count = count + 1
    ABpd.to_csv("duo-regression/" + AB + ".csv")

177
24
78
13
193
42
260
14
79
6
147
37
282
11
224
28
144
29
302
50
222
27
49
8
162
2
154
1
153
33
105
46
117
25
95
35
84
23
58
6
176
14
138
23
189
91
171
18
111
7
2503
2303
163
78
153
2
118
15
109
7
103
35
113
8
228
26
133
2
138
7
157
79
70
9
78
17
375
167
193
40
252
34
102
10
124
18
55
22
171
24
71
33
62
7
160
10
121
20
154
49
92
29
176
15
110
2
24
1
152
11
189
58
191
40
127
8
190
9
74
2
63
21
133
22
195
14
195
48
530
412
184
53
133
8
12
2
187
22
131
10
97
10
2733
2670
93
4
52
10
129
34
503
478
33
9
365
160
89
1
47
16
127
14
168
39
406
314
110
20
210
70
137
14
185
118
187
26
216
29
211
4
78
2
191
4
103
11
91
15
181
16
126
10
71
10
206
53
146
62
203
42
169
15
905
771
152
17
158
25
116
82
125
10
248
164
124
32
785
723
102
18
140
8
235
73
249
56
105
15
115
19
126
19
137
9
73
38
178
175
162
160
159
153
155
152
166
63
165
44
932
771
160
21
228
74
202
75
219
71
170
169